# Generated by Django 2.2.20 on 2022-04-23 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aadhar_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Items_listed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=10)),
                ('lender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Person')),
            ],
        ),
        migrations.CreateModel(
            name='borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField()),
                ('Item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Items_listed')),
            ],
        ),
    ]
