# Generated by Django 3.1.2 on 2022-04-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_id', models.IntegerField()),
                ('borrow_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Items_listed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aadhar_id', models.CharField(max_length=12)),
                ('Item_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=1000)),
                ('type', models.CharField(default='No Category', max_length=50)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aadhar_id', models.CharField(max_length=12)),
                ('email', models.EmailField(default='test@test.com', max_length=1000)),
                ('password', models.CharField(default='password', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField()),
            ],
        ),
    ]
