# Generated by Django 3.1.2 on 2022-04-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_listed',
            name='type',
            field=models.CharField(default='No Category', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=1000),
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='password', max_length=50),
        ),
    ]
